version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    profiles:
      - search 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es01
    ports:
      - "5601:5601"
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    profiles:
      - search
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1234!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - data02:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
volumes:
  data01:
    driver: local
  data02:
    driver: local